/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BalanceGameInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COST"
      | "GAMEINDEX"
      | "createVote"
      | "findGameById"
      | "isContinue"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
      | "vote"
      | "whiteList"
      | "whitelistUpdate"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GameFinished"
      | "NewGame"
      | "NewVote"
      | "OwnershipTransferred"
      | "WhiteListUpdate"
  ): EventFragment;

  encodeFunctionData(functionFragment: "COST", values?: undefined): string;
  encodeFunctionData(functionFragment: "GAMEINDEX", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createVote",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "findGameById",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isContinue",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "whiteList",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistUpdate",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "COST", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "GAMEINDEX", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "findGameById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isContinue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "whiteList", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "whitelistUpdate",
    data: BytesLike
  ): Result;
}

export namespace GameFinishedEvent {
  export type InputTuple = [gameId: BigNumberish];
  export type OutputTuple = [gameId: bigint];
  export interface OutputObject {
    gameId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewGameEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    questionA: string,
    questionB: string,
    deadline: BigNumberish,
    creator: AddressLike
  ];
  export type OutputTuple = [
    gameId: bigint,
    questionA: string,
    questionB: string,
    deadline: bigint,
    creator: string
  ];
  export interface OutputObject {
    gameId: bigint;
    questionA: string;
    questionB: string;
    deadline: bigint;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewVoteEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    votedAddress: AddressLike,
    voteOpttion: BigNumberish
  ];
  export type OutputTuple = [
    gameId: bigint,
    votedAddress: string,
    voteOpttion: bigint
  ];
  export interface OutputObject {
    gameId: bigint;
    votedAddress: string;
    voteOpttion: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WhiteListUpdateEvent {
  export type InputTuple = [arg0: AddressLike, status: boolean];
  export type OutputTuple = [arg0: string, status: boolean];
  export interface OutputObject {
    arg0: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BalanceGame extends BaseContract {
  connect(runner?: ContractRunner | null): BalanceGame;
  waitForDeployment(): Promise<this>;

  interface: BalanceGameInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COST: TypedContractMethod<[], [bigint], "view">;

  GAMEINDEX: TypedContractMethod<[], [bigint], "view">;

  createVote: TypedContractMethod<
    [_questionA: string, _questionB: string, _deadline: BigNumberish],
    [bigint],
    "payable"
  >;

  findGameById: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, bigint, string] & {
        id: bigint;
        questionA: string;
        questionB: string;
        voteCountA: bigint;
        voteCountB: bigint;
        totalETH: bigint;
        deadline: bigint;
        creator: string;
      }
    ],
    "view"
  >;

  isContinue: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  vote: TypedContractMethod<
    [_gameId: BigNumberish, _voteOption: BigNumberish],
    [void],
    "payable"
  >;

  whiteList: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  whitelistUpdate: TypedContractMethod<
    [_newAddress: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COST"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GAMEINDEX"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createVote"
  ): TypedContractMethod<
    [_questionA: string, _questionB: string, _deadline: BigNumberish],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "findGameById"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, bigint, string] & {
        id: bigint;
        questionA: string;
        questionB: string;
        voteCountA: bigint;
        voteCountB: bigint;
        totalETH: bigint;
        deadline: bigint;
        creator: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isContinue"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [_gameId: BigNumberish, _voteOption: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "whiteList"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "whitelistUpdate"
  ): TypedContractMethod<
    [_newAddress: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "GameFinished"
  ): TypedContractEvent<
    GameFinishedEvent.InputTuple,
    GameFinishedEvent.OutputTuple,
    GameFinishedEvent.OutputObject
  >;
  getEvent(
    key: "NewGame"
  ): TypedContractEvent<
    NewGameEvent.InputTuple,
    NewGameEvent.OutputTuple,
    NewGameEvent.OutputObject
  >;
  getEvent(
    key: "NewVote"
  ): TypedContractEvent<
    NewVoteEvent.InputTuple,
    NewVoteEvent.OutputTuple,
    NewVoteEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "WhiteListUpdate"
  ): TypedContractEvent<
    WhiteListUpdateEvent.InputTuple,
    WhiteListUpdateEvent.OutputTuple,
    WhiteListUpdateEvent.OutputObject
  >;

  filters: {
    "GameFinished(uint256)": TypedContractEvent<
      GameFinishedEvent.InputTuple,
      GameFinishedEvent.OutputTuple,
      GameFinishedEvent.OutputObject
    >;
    GameFinished: TypedContractEvent<
      GameFinishedEvent.InputTuple,
      GameFinishedEvent.OutputTuple,
      GameFinishedEvent.OutputObject
    >;

    "NewGame(uint256,string,string,uint256,address)": TypedContractEvent<
      NewGameEvent.InputTuple,
      NewGameEvent.OutputTuple,
      NewGameEvent.OutputObject
    >;
    NewGame: TypedContractEvent<
      NewGameEvent.InputTuple,
      NewGameEvent.OutputTuple,
      NewGameEvent.OutputObject
    >;

    "NewVote(uint256,address,uint8)": TypedContractEvent<
      NewVoteEvent.InputTuple,
      NewVoteEvent.OutputTuple,
      NewVoteEvent.OutputObject
    >;
    NewVote: TypedContractEvent<
      NewVoteEvent.InputTuple,
      NewVoteEvent.OutputTuple,
      NewVoteEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "WhiteListUpdate(address,bool)": TypedContractEvent<
      WhiteListUpdateEvent.InputTuple,
      WhiteListUpdateEvent.OutputTuple,
      WhiteListUpdateEvent.OutputObject
    >;
    WhiteListUpdate: TypedContractEvent<
      WhiteListUpdateEvent.InputTuple,
      WhiteListUpdateEvent.OutputTuple,
      WhiteListUpdateEvent.OutputObject
    >;
  };
}
